defmodule Protox.Generate do
  @moduledoc false

  defmodule FileContent do
    @moduledoc false
    @type t() :: %__MODULE__{name: String.t(), content: iodata()}
    defstruct([:name, :content])
  end

  @spec generate_module_code(
          [Path.t()],
          String.t(),
          boolean(),
          [Path.t()],
          keyword()
        ) :: {:ok, [FileContent.t()]} | {:error, any()}
  def generate_module_code(files, output_path, multiple_files, include_paths, opts \\ [])
      when is_list(files) and is_binary(output_path) and is_boolean(multiple_files) do
    paths =
      case include_paths do
        [] -> nil
        _other_paths -> Enum.map(include_paths, &Path.expand/1)
      end

    case launch_protoc(files, paths) do
      {:ok, file_descriptor_set} ->
        {:ok, definition} = Protox.Parse.parse(file_descriptor_set, opts)
        code = Protox.Define.define(definition, opts)
        {:ok, generate_files(output_path, code, multiple_files)}

      {:error, msg} ->
        {:error, msg}
    end
  end

  # -- Private

  defp launch_protoc(files, paths) do
    files
    |> Enum.map(&Path.expand/1)
    |> Protox.Protoc.run(paths)
  end

  defp generate_files(output_path, code, false = _multiple_files) do
    [
      %FileContent{
        name: output_path,
        content: generate_file_content(code)
      }
    ]
  end

  defp generate_files(output_path, code, true = _multiple_files) do
    # Protox.Define.define outputs a block, we thus have to extract the content
    # on which we can iterate.
    {:__block__, _meta, block} = code

    Enum.map(block, fn {:defmodule, _meta, [module_name | _rest]} = module_code ->
      snake_module_name =
        module_name
        |> Module.split()
        |> Enum.map_join("_", &Macro.underscore/1)

      %FileContent{
        name: Path.join(output_path, snake_module_name <> ".ex"),
        content: generate_file_content(module_code)
      }
    end)
  end

  defp generate_file_content(code) do
    [
      "# Code generated by protox. Don't edit.\n",
      "# credo:disable-for-this-file\n",
      code
      |> Macro.to_string()
      |> fold_trivial_defs()
      |> Code.format_string!(),
      "\n"
    ]
  end

  @max_line_length 98

  @doc false
  # Macro.to_string/1 always renders do/end blocks. Fold the trivial ones
  # (a def with a single-line body) into the keyword form, which the
  # formatter preserves: `def default(), do: {:ok, nil}`.
  @spec fold_trivial_defs(String.t()) :: String.t()
  def fold_trivial_defs(code) do
    code
    |> String.split("\n")
    |> fold_trivial_defs([])
    |> Enum.reverse()
    |> Enum.join("\n")
  end

  defp fold_trivial_defs([head, body, tail | rest], acc) do
    with [_all, indent, definition] <- Regex.run(~r/^(\s*)(defp? .*[^,]) do$/, head),
         true <- tail == indent <> "end",
         body = String.trim(body),
         # Skip bodies that themselves use a block or clause syntax.
         false <- String.contains?(body, [" do", "do:", "->", "#"]),
         folded = "#{indent}#{definition}, do: #{body}",
         true <- String.length(folded) <= @max_line_length do
      fold_trivial_defs(rest, [folded | acc])
    else
      _cannot_fold -> fold_trivial_defs([body, tail | rest], [head | acc])
    end
  end

  defp fold_trivial_defs(remaining_lines, acc), do: Enum.reverse(remaining_lines, acc)
end
