repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-merge-conflict
      - id: mixed-line-ending
  - repo: https://github.com/ahamez/pre-commit-elixir-hooks.git
    rev: v1.0.0
    hooks:
      - id: elixir-mix-format
        stages: [pre-commit]
      - id: elixir-mix-credo
        stages: [pre-commit]
      - id: elixir-mix-deps-check-unused
        stages: [pre-push]
      - id: elixir-mix-dialyzer
        stages: [pre-push]
      - id: elixir-mix-test
        args: ["--exclude", "properties"]
        stages: [pre-push]
